name: mybinder-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - openjdk=11
  - pip
  - pip:
      - asttokens==3.0.0
      - certifi==2025.8.3
      - charset-normalizer==3.4.2
      - click==8.2.1
      - colorama==0.4.6
      - comm==0.2.3
      - debugpy==1.8.16
      - decorator==5.2.1
      - executing==2.2.0
      - idna==3.10
      - ipykernel==6.30.1
      - ipython==8.18.1
      - ipython_pygments_lexers==1.1.1
      - jedi==0.19.2
      - joblib==1.5.1
      - jupyter_client==8.6.3
      - jupyter_core==5.8.1
      - matplotlib-inline==0.1.7
      - nest-asyncio==1.6.0
      - nltk==3.9.1
      - numpy==2.3.2
      - packaging==25.0
      - pandas==2.3.1
      - parso==0.8.4
      - platformdirs==4.3.8
      - prompt_toolkit==3.0.51
      - psutil==7.0.0
      - pure_eval==0.2.3
      - Pygments==2.19.2
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyzmq==27.0.1
      - regex==2025.7.34
      - requests==2.32.4
      - sentistrength==0.0.9
      - six==1.17.0
      - stack-data==0.6.3
      - textblob==0.19.0
      - git+https://github.com/markuskiller/textblob-de.git@e04c59ed9ad41e89241c79828449e89d103fb294
      - tornado==6.5.1
      - tqdm==4.67.1
      - traitlets==5.14.3
      - tzdata==2025.2
      - urllib3==2.5.0
      - vaderSentiment==3.3.2
      - wcwidth==0.2.13
